export const CREATE_ROOM = 'CREATE_ROOM';

export const JOIN_ROOM = 'JOIN_ROOM';

export const LEAVE_ROOM = 'LEAVE_ROOM';

export const ROOM_CREATED = 'ROOM_CREATED';

export const ROOM_JOINED = 'ROOM_JOINED';

export const ROOM_LEFT = 'ROOM_LEFT';

export const CONNECTION = 'CONNECTION';

export const UPDATE_SOCKET_ID = 'UPDATE_SOCKET_ID';

export const NEW_USER_ROOM_JOINED = 'NEW_USER_ROOM_JOINED';

export const CHECK_ROOM_USER = 'CHECK_ROOM_USER';

export const SPAWNED_LOCATION = 'SPAWNED_LOCATION';

export const SPAWN_NEW_LOCATION = 'SPAWN_NEW_LOCATION';

export const GET_LEADERBOARD_SCORE = 'GET_LEADERBOARD_SCORE';
