version: '3.7'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: clickster-nodejs-server
    container_name: clickster-nodejs-server
    env_file: ./server/.env
    ports:
      - 5000:5000
  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: clickster-react-app
    container_name: clickster-react-app
    ports:
      - 3000:80